#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-Test-MockTime-HiRes
Version  : 0.08
Release  : 7
URL      : https://cpan.metacpan.org/authors/id/T/TA/TARAO/Test-MockTime-HiRes-0.08.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TA/TARAO/Test-MockTime-HiRes-0.08.tar.gz
Summary  : 'Replaces actual time with simulated high resolution time'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-MockTime-HiRes-license = %{version}-%{release}
Requires: perl-Test-MockTime-HiRes-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(ExtUtils::Config)
BuildRequires : perl(ExtUtils::Helpers)
BuildRequires : perl(ExtUtils::InstallPaths)
BuildRequires : perl(Module::Build::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build Status](https://travis-ci.org/tarao/perl5-Test-MockTime-HiRes.svg?branch=master)](https://travis-ci.org/tarao/perl5-Test-MockTime-HiRes)
# NAME

%package dev
Summary: dev components for the perl-Test-MockTime-HiRes package.
Group: Development
Provides: perl-Test-MockTime-HiRes-devel = %{version}-%{release}
Requires: perl-Test-MockTime-HiRes = %{version}-%{release}

%description dev
dev components for the perl-Test-MockTime-HiRes package.


%package license
Summary: license components for the perl-Test-MockTime-HiRes package.
Group: Default

%description license
license components for the perl-Test-MockTime-HiRes package.


%package perl
Summary: perl components for the perl-Test-MockTime-HiRes package.
Group: Default
Requires: perl-Test-MockTime-HiRes = %{version}-%{release}

%description perl
perl components for the perl-Test-MockTime-HiRes package.


%prep
%setup -q -n Test-MockTime-HiRes-0.08
cd %{_builddir}/Test-MockTime-HiRes-0.08

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-MockTime-HiRes
cp %{_builddir}/Test-MockTime-HiRes-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Test-MockTime-HiRes/c9909d7e79b87a77ce2e248e8115f4b0f11b71ed || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::MockTime::HiRes.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-MockTime-HiRes/c9909d7e79b87a77ce2e248e8115f4b0f11b71ed

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
